clinicApp/urls.py
from django.urls import path, include
app_name = 'clinicApp'
from .import views
urlpatterns = [
    path('', views.home, name="home"),
    path('signup/',views.signupPage, name="signup"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutPage, name="logout"),
    path('doctor/', views.doctor, name="doctor"),
    path('doctor/doctordetail/<int:pk>', views.doctorDetail, name="doctorDetail"),
    path('pharmacy/', views.pharmacy, name="pharmacy"),
    path('carts/', views.add_to_cart, name="cart"),
    path('showcart/',views.show_cart, name="show_cart"),
    path('pluscart/', views.plus_cart, name="pluscart"),
    path('minuscart/',views.minus_cart, name="minuscart"),
    path('removecart',views.remove_cart, name="removecart"),
    path('checkout/', views.checkout, name="checkout"),
    path('blog/', views.blog, name='blog'),
    path('dashboard/', views.dashboard, name="dashboard"),
    
]

peoplecare/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clinicApp.urls', namespace='clinicApp')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

clinicApp/models.py
from django.db import models
from django.urls import *
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# Create your models here.
class Customer(models.Model):
    customer = models.OneToOneField(User, on_delete = models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    phone = models.IntegerField()
    address = models.CharField(max_length=255)
    email = models.EmailField()


class Patient(models.Model):
    patientImage = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=20)
    detail = models.CharField(max_length=300)

    class Meta:
        verbose_name = "Patients"
        verbose_name_plural = "Patients"
    def __str__(self):
        return self.name

class DoctorCategories(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "DoctorCategories"
        verbose_name_plural = "DoctorCategories"

    def __str__(self):
        return self.name

class Doctors(models.Model):
    doctorImage = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=20)
    speciality = models.CharField(max_length=100)
    designation = models.CharField(max_length=200)
    Education = models.CharField(max_length=400)
    # categories = models.ForeignKey(DoctorCategories, on_delete= models.CASCADE, null=True, blank=True, default=2)

    class Meta:
        verbose_name = "Doctors"
        verbose_name_plural = "Doctors"

    def __str__(self):
        return self.name
    
CATEGORY_CHOICES = (
    ('Covid Essentials', 'Covid Essentials'),
    ('Ayurvedic', 'Ayurvedic'),
    ('Homeopathy', 'Homeopathy'),
    ('Fitness', 'Fitness'),
    ('Surgical', 'Surgical'),
    ('Sexual Wellness', 'Sexual Wellness')
)
class Pharmacy(models.Model):
    productImage = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    category = models.CharField(max_length=50, choices= CATEGORY_CHOICES)
    
    class Meta:
        verbose_name = "Pharmacy"
        verbose_name_plural = "Pharmachies"
        ordering = ('name',)

    def __str__(self):
        return str(self.id)


class Order(models.Model):
    customer =  models.ForeignKey(User,on_delete = models.CASCADE )
    product = models.ForeignKey(Pharmacy, on_delete = models.CASCADE)
    quantity = models.IntegerField(default=1)
    order_date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return str(self.id)


User = get_user_model()

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField(max_length=100)
    detail = models.TextField()
    time_stamp = models.DateTimeField(auto_now_add=True)
    comment_count = models.IntegerField(default=0)
    author = models.ForeignKey(Author, on_delete = models.CASCADE)
    thumbnail = models.ImageField()
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField()

    def __str__(self):
        return self.title

class Newsletter(models.Model):
    email = models.EmailField()
    time_stamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Newsletters"
        verbose_name_plural = "Newsletters"

    def __str__(self):
        return self.email

clinicApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="" ,widget=forms.TextInput(attrs={'class': 'form-control mt-1 mb-1', 'placeholder': 'Enter your Email'}))
    
    first_name = forms.CharField(label="", max_length=30,  widget=forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Enter your First Name'}))
    last_name = forms.CharField(label="", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Enter your Last Name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def  __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

       

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Enter Your Username'
        self.fields['username'].label=''
        self.fields['username'].help_text = '<span class="form-text text-muted " style="margin-top:-20px;"> <small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'
       

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Enter Your Password'
        self.fields['password1'].label=''
        self.fields['password1'].help_text = '<small class=""><ul class="form-text text-muted " style="list-style:none; margin-top:-20px;"><li style="list-style:none; color:red">Your password cant be too similar to your other personal information.</li><li style="list-style:none; color:red">Your password must contain at least 8 characters.</li><li style="list-style:none; color:red"> Your password cant be a commonly used password.</li><li style="list-style:none; color:red"> Your password cant be entirely numeric.</li></ul></small>'

        self.fields['password2'].widget.attrs['class'] = 'form-control '
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Your Password'
        self.fields['password2'].label=''
        self.fields['password2'].help_text = '<span class="form-text text-muted" style="list-style:none; margin-top: -20px"> <small>Enter the same password as before, for verification.</small></span>'

clinicApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm  
from .models import *
from .forms import SignUpForm
from django.core.paginator import Paginator
from django.db.models import Q
# from django.http import jsonResponse
from django.http import JsonResponse
import json
from django.core.serializers.json import DjangoJSONEncoder
# from .cart import Cart
# Create your views here.


def signupPage(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request,username=username, password = password)
            login(request, user)
            return redirect ("clinicApp:login") 
    else:
        form = SignUpForm()
    return render(request, 'clinicApp/signup.html',{'form':form})
def loginPage(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password = password)
        if user is not None:
            login(request, user)
            return redirect("clinicApp:home")
        else:
            messages.warning(request, "Username or Password is incorrect")
            return redirect("clinicApp:login")
    else:      
        return render(request, 'clinicApp/login1.html', {})


def logoutPage(request):
    logout(request)
    return redirect('clinicApp:home')

def home(request):
    patient = Patient.objects.all()
    return render(request, 'clinicApp/index.html', {'patient':patient})
def doctor(request):
    doctor = Doctors.objects.all()
    paginator = Paginator(doctor,9)
    page = request.GET.get('page')
    doctor = paginator.get_page(page)
    return render(request, 'clinicApp/doctors.html', {'doctor':doctor})

def doctorDetail(request,pk):
    doctorDetail = Doctors.objects.get(id=pk)
    context = {'doctorDetail':doctorDetail}
    return render(request, 'clinicApp/doctorDetail.html', context)
def pharmacy(request):
    pharmacy = Pharmacy.objects.all()
    ordering = request.GET.get('ordering', "")
    item_name = request.GET.get('itemname')
    
    if item_name != '' and item_name is not None:
        pharmacy = pharmacy.filter(name__icontains = item_name)
    if ordering:
        pharmacy = pharmacy.order_by(ordering) 
    # Paginator
    paginator = Paginator(pharmacy, 12)
    page = request.GET.get('page')
    pharmacy = paginator.get_page(page)
    return render(request, 'clinicApp/pharmacy.html', {'pharmacy':pharmacy})

def add_to_cart(request):
    user = request.user
    prod_id = request.GET.get('prod_id') 
    product = Pharmacy.objects.get(id = prod_id) 
    Order(customer = user, product = product).save()
    return redirect('clinicApp:show_cart')

def show_cart(request):
    if request.user.is_authenticated:
        user = request.user
        cart = Order.objects.filter(customer=user)
        print(cart)
        total = 0
        sub_total = 0
        shipping=200
        coupon_discount=0
        grant_total = 0
        cart_product = [i for i in Order.objects.all() if i.customer == user]
        # print(cart_product)
        if cart_product:
            for i in cart_product:
                total  = (i.quantity * i.product.price)
                sub_total = sub_total + total
                grant_total = sub_total + shipping - coupon_discount
                print(total)
                
        return render(request, 'clinicApp/cart.html', {'cart':cart, 'total':total, 'sub_total':sub_total, 'grant_total':grant_total})

    else:
        return render(request, "clinicApp/empty.html", {})

def plus_cart(request):

    if request.method == "GET":
        prod_id = request.GET.get('prod_id')
        # print(prod_id)
        c = Order.objects.get (Q(product = prod_id) & Q(customer = request.user))
        c.quantity += 1
        c.save()
        total = 0
        sub_total = 0
        shipping=200
        coupon_discount=0
        cart_product = [i for i in Order.objects.all() if i.customer == request.user]
        for i in cart_product:
            total  = (i.quantity * i.product.price)
            # total = total+total
            sub_total = sub_total + total
           

        data ={
            'sub_total':sub_total,
            'quantity':c.quantity,
            'grant_total': sub_total + shipping - coupon_discount
           
        }
        return JsonResponse(data)


def minus_cart(request):
    if request.method == "GET":
        prod_id = request.GET.get('prod_id')
        # print(prod_id)
        c = Order.objects.get (Q(product = prod_id) & Q(customer = request.user))
        c.quantity -= 1
        c.save()
        total = 0
        sub_total = 0
        shipping=200
        coupon_discount=0
        cart_product = [i for i in Order.objects.all() if i.customer == request.user]
        for i in cart_product:
            total  = (i.quantity * i.product.price)
            # total = total+total
            sub_total = sub_total + total

        data ={
            'sub_total':sub_total,
            'quantity':c.quantity,
            'grant_total':  sub_total + shipping - coupon_discount

        }
        return JsonResponse(data)


def remove_cart(request):
    if request.method == "GET":
        prod_id = request.GET.get('prod_id')
        # print(prod_id)
        c = Order.objects.get (Q(product = prod_id) & Q(customer = request.user))
        c.delete()
        total = 0
        sub_total = 0
        shipping=200
        coupon_discount=0
        cart_product = [i for i in Order.objects.all() if i.customer == request.user]
        for i in cart_product:
            total  = (i.quantity * i.product.price)
            # total = total+total
            sub_total = sub_total + total
        
        data ={
            'sub_total':sub_total,
            'grant_total':  sub_total + shipping - coupon_discount
        }
       
        return JsonResponse(data)
    

def checkout(request):
    return render(request, 'clinicApp/checkout.html', {})

def blog(request):
    if request.method == "POST":
        email = request.POST["email"]
        newsletter = Newsletter()
        newsletter.email = email
        newsletter.save()
    featured = Post.objects.filter(featured = True)
    latest = Post.objects.order_by('-time_stamp')[0:3]
    return render(request, 'clinicApp/blog.html', {'post':featured, 'latest':latest})


def dashboard(request):
    return render(request, 'clinicApp/adminsite.html', {})


        
   
    

clinicApp/templates/clinicApp/adminsite.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" text="text/css" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/f2be6d220c.js" crossorigin="anonymous"></script>
</head>
<body>
    <section class="menu">
        <div class="adminlogo">
            <img src="{% static 'images/Peoples-Care-Logo.png' %}" alt="" srcset="">
            
        </div>
        <div class="sideitems" style="display:flex ;flex-direction: column; justify-content: space-between; ">
        <div>
            
            <li class="active1">
                <i class="fa fa-address-card"></i>
                <a href="">Dashboard</a>
            </li>
            <li>
                <i class="fa fa-calendar-check"></i>
                    <a href=""> My Appointment</a>
                
            </li>
            <li>
                <i class="fas fa-heart"></i>
                    <a href="">My Wishlist</a>
                </i>
            </li>
            <li>
                <i class="fas fa-shopping-cart"></i>
                <a href="">My Cart</a>
            </li>
            <li>
                <i class="fa fa-cog"></i>
                <a href=""> Setting</a>
            </li>
            <li>
                <!-- <i class="fa fa-cog"></i> -->
                <i class="fa fa-rotate-left"></i>
                <a href="{% url 'clinicApp:home' %}"> Go To Home</a>
            </li>
          
        </div>
        <div style="margin-top: 40px;">
            
            <li class="" style="margin-top: 30px; background: red;">
               
                <i class="uil uil-signout"></i>
                <a href="{% url 'clinicApp:logout' %}">Log Out</a>
            </li>
        </div>
    </section>
    <section class="mainsection">
        <div class="navigationsection">
            <div class="n1">
                <div>
                    <i id="btnMenu" class="fa fa-bars"></i>
                </div>
                <div class="nameacc">
                    <h5>Your Account</h5>
                   </div>
            </div>
          
        
        <div class="dashboardprofile">
            <i class="fas fa-bell"></i>
            <img src="{% static 'images/pat1.png' %}" alt="">
        </div>
    </div>
  

 
        <h3 class="i-name">My Dashboard</h3>
        <div class="values">
            <div class="valuebox">
                <i class="fa fa-calendar-check"></i>
                <div>
                    <h4 style="margin-right: 15px;">5</h4>
                    <span>Total Appointments</span>
                    
                </div>
            </div>
            <div class="valuebox">
                <i class="fas fa-heart"></i>
                <div>
                    <h4 style="margin-right: 15px;">5</h4>
                    <span>Total Wishlists</span>
                    
                </div>
            </div>
            <div class="valuebox">
                <i class="fas fa-shopping-cart"></i>
                <div>
                    <h4 style="margin-right: 15px;">5</h4>
                    <span>Total Orders</span>
                    
                </div>
            </div>
          
        </div>
    
        <div class="ordersboard">
            <h3 class="i-name">My Recent Orders</h3>
            <table width="100%">
                <thead>
                    <tr>
                        <td>Order ID</td>
                        <td>Product Name</td>
                        <td>Quantity</td>
                        <td>Payment Status</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            1
                        </td>
                        <td class="orderProduct">
                            <img src="{% static 'images/pat1.png' %}" alt="">
                            <div class="proddesc">
                                <h5>Product1</h5>
                                <p>Homopathy</p>
                            </div>
                        </td>
                        <td class="quantity desc">
                             <h5>5</h5>
                             <p>Rs.3000</p>
                        </td>
                        <td class="action">
                            <p>True</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            1
                        </td>
                        <td class="orderProduct">
                            <img src="{% static 'images/pat2.png' %}" alt="">
                            <div class="proddesc">
                                <h5>Product1</h5>
                                <p>Homopathy</p>
                            </div>
                        </td>
                        <td class="quantity desc">
                             <h5>5</h5>
                             <p>Rs.3000</p>
                        </td>
                        <td class="action">
                            <p>True</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            1
                        </td>
                        <td class="orderProduct">
                            <img src="{% static 'images/pqt3.png' %}" alt="">
                            <div class="proddesc">
                                <h5>Product1</h5>
                                <p>Homopathy</p>
                            </div>
                        </td>
                        <td class="quantity desc">
                             <h5>5</h5>
                             <p>Rs.3000</p>
                        </td>
                        <td class="action">
                            <p>True</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            1
                        </td>
                        <td class="orderProduct">
                            <img src="{% static 'images/pqt4.png' %}" alt="">
                            <div class="proddesc">
                                <h5>Product1</h5>
                                <p>Homopathy</p>
                            </div>
                        </td>
                        <td class="quantity desc">
                             <h5>5</h5>
                             <p>Rs.3000</p>
                        </td>
                        <td class="action">
                            <p>True</p>
                        </td>
                    </tr>
                </tbody>

            </table>
        </div>
    </section>
    <script>
        $('#btnMenu').click(function(){
            $('.menu').toggleClass("active");
        })
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

clinicApp/templates/clinicApp/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" media="screen" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <script src="https://kit.fontawesome.com/f2be6d220c.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>WebApp</title>
</head>
<body>
   
        <a class="logo" title="CareforYou Clinic" href="{% url 'clinicApp:home' %}" > <span>Care for you</span></a>   
       
        <!-- <nav>
            <ul>
                <li>
                    <a title="home" href="">Home</a>
                    
                </li>
              
                <li>
                    <a title="services" aria-haspopup="true" href="">Services</a>
                    <ul>
                        <li>
                            <a title="emergency" href="">Medical Staff</a>
                           
                        </li>
                      
                        
                        <li>
                            <a title="transplant" href="">Pharmacy</a>
                        </li>
                       
                    </ul>
                </li>

                <li style="margin: -1.3px;">
                <a href="">
                    <div class="fas fa-shopping-cart fa-lg" id="shopping"><h5 class="cart-item-count"><strong></strong></h5></div></a></li>
                <li>
                    <a href="">
                        <div class="fas fa-user fa-lg" id="user"></div>
                    </a>
                    
                    
                </li>
            </ul>
        </nav> -->
        <nav>
            <ul>
                <li>
                    <a title="home" href="{% url 'clinicApp:home' %}">Home</a>
                    
                </li>
              
                <li>
                    <a title="services" aria-haspopup="true" href="{% url 'clinicApp:home' %}" style="z-index: 11; margin-bottom: 1px;">Services</a>
                    <ul>
                        <li style="margin-top: 1px;">
                            <a title="emergency" href="{% url 'clinicApp:doctor' %}" style="z-index: 11;  margin-top:-5px;">Medical Staff</a>
                           
                        </li>
                      
                        
                        <li>
                            <a title="transplant" href="{% url 'clinicApp:pharmacy' %}" style="z-index: 11;">Pharmacy</a>
                        </li>
                       
                    </ul>
                </li>
                <li>
                    <a title="blog" href="{% url 'clinicApp:blog' %}">Blog</a>
                    
                </li>
              

                <li style="margin: -1.3px;">
                <a href="{% url 'clinicApp:show_cart' %}">
                    <div class="fas fa-shopping-cart fa-lg" id="cart"><h5 class=""></h5></div></a></li>
                <li class="">
                    {% if user.is_authenticated %}
                    <a href="{% url 'clinicApp:dashboard'  %}">
                        <div class="fas fa-user fa-lg" id="user"><span> {{request.user}}</span> </div>
                    </a>
                    {% else %}
                    <a href="{% url 'clinicApp:dashboard'  %}">
                        <div class="fas fa-user fa-lg" id="user"><span></span> </div>
                    </a>
                    {% endif %}
                    
                </li>
                <div class="rightblock" style="display:flex; justify-content:flex-end;">
                    {% if user.is_authenticated %}
                    <li class="">
                        <a title="transplant" href="{% url 'clinicApp:logout' %}">Logout</a>
                        
                    </li>
                    {% else %}
                    <li class="">
                        <a title="transplant" href="{% url 'clinicApp:signup' %}">Sign UP</a>
                        
                        
                    </li>
                    <li class="">
                        <a title="transplant" href="{% url 'clinicApp:login' %}">Login</a> 
                    </li>
                    {% endif %}
                </div>
              
               
            </ul>
            
        </nav>
        {% block home %}
        {% endblock %}
        {% block doctors %}
        {% endblock %}
        {% block doctorDetail %}
        {% endblock %}
        {% block pharmacy %}
        {% endblock %}
        {% block blog %}
        {% endblock %}
        {% block cart %}
        {% endblock %}
        {% block checkout %}
        {% endblock %}
        {% block empty %}
        {% endblock %}


        <footer>
            <div class="icons">
                <i class="fab fa-facebook"></i>
                <i class="fab fa-instagram"></i>
                <i class="fab fa-twitter-square"></i>
            </div>
            <div class="content">
                <a href="" title="Privacy Policy">Privacy Policy</a>
                <a href="" title="Term of Service">Terms of Service</a>
           
            &copy; CareforYou
        </div>
        </footer>
    </div>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js" integrity="sha512-A7AYk1fGKX6S2SsHywmPkrnzTZHrgiVT7GcQkLGDe2ev0aWb8zejytzS8wjo7PGEXKqJOrjQ4oORtnimIRZBtw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
     -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block js %}
    {% endblock %}

    {% block script %}
  
    {% endblock %}
    <!-- <script>
        var slide = document.getElementById('slide');
        var left = document.getElementById('right');
        var right = document.getElementById('left');
        let x = 0
        left.onclick = function(){
            if (x>= "-300"){
                x = x-300;
            slide.style.top = x + "px";
            }
            
        }
        right.onclick = function(){
            if (x <0){
                x = x+300;
            slide.style.top = x + "px";
            }
            
        }
    </script> -->
    <script>
        AOS.init({
            duration:1000,
            delay:400
        })
    </script>
    
</body>
</html>

clinicApp/templates/clinicApp/empty.html
{% extends 'clinicApp/base.html' %}
{% load static %}

{% block empty %}
<section style="margin-top: 5%; text-align: center;">
    <img src="{% static 'images/nocart.png' %}" alt="" style="border: 1px solid black; border-radius: 25%;">
<h5 class="mt-3">Sorry, <span  style="color: rgba(101, 37, 37, 0.533); font-size: larger;"> {{request.user}}</span> your cart is Empty.</h5>
</section>
{% endblock %}
      